$text_color = rgb(D3C6AA)
$entry_background_color = rgb(272E33)
$entry_border_color = rgb(414B50)
$entry_color = rgb(D3C6AA)
$accent = rgb(A7C080)
$font_family = JetBrains Mono
$font_symbols = Iosevka Nerd Font Mono

background {
    path = ~/.config/Ghibli.png
    blur_passes = 3
    blur_size = 7
    brightness = 0.75
}

input-field {
    monitor =
    size = 280, 60
    outline_thickness = 2
    dots_size = 0.1
    dots_spacing = 0.3
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    font_color = $entry_color
    placeholder_text = Password...
    fail_color = rgb(E67E80)
    fail_text = Login failed. Please try again.
    rounding = 30
    position = 0, 20
    halign = center
    valign = center
}

label { # Clock
    monitor =
    text = cmd[update:1000] date '+%I:%M'
    shadow_passes = 1
    shadow_boost = 0.5
    color = $text_color
    font_size = 140
    font_family = $font_family
    font_weight = bold
    position = 0, 300
    halign = center
    valign = center
}

label { # Date
    monitor =
    text = cmd[update:1000] date '+%A, %B %d'
    shadow_passes = 1
    shadow_boost = 0.5
    color = $text_color
    font_size = 22
    font_family = $font_family
    font_weight = bold
    position = 0, 160
    halign = center
    valign = center
}

label { # lock icon
    monitor =
    text = 
    shadow_passes = 1
    shadow_boost = 0.5
    color = $accent
    font_size = 32
    font_family = $font_symbols
    position = 0, -360
    halign = center
    valign = center
}

label { # "Locked" text
    monitor =
    text = Locked
    shadow_passes = 1
    shadow_boost = 0.5
    color = $text_color
    font_size = 14
    font_family = $font_family
    position = 0, 45
    halign = center
    valign = bottom
}
